[workflows.mail]
group = "work"
script = "open -a 'Canary Mail'"
duration = "5s"
log = "mail"

[workflows.break]
group = "work"
script = "sleep 10 && pmset displaysleepnow"
duration = "1m"
log = "break"
